### ISSUE TITLE
Label not being removed on issue close event

### ISSUE THREAD

**Issue by ben93riggs** [andymckay/labeler#10]
Is this a configuration error on my end?

`labeler.yml`
```
# This workflow fires when an issue is closed, and removes the "in progress" label
name: Remove 'in progress' label from closed issue

on:
  issues:
    types: [closed]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
    - uses: andymckay/labeler@1.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        remove-labels: "bug"
```

`output`
```Run andymckay/labeler@1.0.2
  with:
    repo-token: ***
    remove-labels: bug
RequestError [HttpError]: Validation Failed
    at /home/runner/work/_actions/andymckay/labeler/1.0.2/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async label (/home/runner/work/_actions/andymckay/labeler/1.0.2/label.js:48:3) {
  name: 'HttpError',
  status: 422,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '177',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 25 Mar 2020 22:14:11 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '422 Unprocessable Entity',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
```
