### ISSUE TITLE
Cannot read number of 'undefined' Project Card event

### ISSUE THREAD

**Issue by rodrigondec** [andymckay/labeler#12]
The same error happen from issue #6 when this action is called with `project_card` event. I would like to use it to add a label to my issue from a `project_car` event.

```yml
name: project-automation

on:
  project_card:
    types: [moved]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: label issues from 'In progress'
        uses: andymckay/labeler@1.0.2
        if: |
          github.event_name == 'project_card' &&
          (
            github.event.project_card.column_id == 9034006
          )
        with:
          repo-token: ${{secrets.GH_TOKEN}}
          add-labels: "c"
```

![image](https://user-images.githubusercontent.com/3301060/81130401-fecea300-8f1d-11ea-988e-546be76bd63f.png)
