### ISSUE TITLE
Suggestion: Remove all labels

### ISSUE THREAD

**Issue by sburkett** [andymckay/labeler#20]
Somewhat self-explanatory. We have a ton of labels, and when we add new ones, we often have to go back through our actions and fixup all sorts of stuff, remembering to add new labels, use new label names if they get changed, etc. But it would super handy to be able to do something like this:

```
        uses: andymckay/labeler@1.0.2
        with:
          remove-all-labels: true
          add-labels: 'XYZ'
```
