### ISSUE TITLE
Failed to run behind a proxy server

### ISSUE THREAD

**Issue by sidezrw** [andymckay/labeler#22]
When the runner for the workload is behind a proxy server, this action fails to connect to GitHub.

This is the workload yaml:

```yaml
name: issue-labeling-automation

on:
  project_card:
    types: [moved]

jobs:
  remove_old_labels:
    runs-on: ubuntu-latest
    steps:
      - name: remove old labeling
        uses: andymckay/labeler@master
        with:
          remove-labels: "To Do, Assigned, In Progress, Testing, Done"
      
  add_to_do_label:
    needs: remove_old_labels
    # Change column ID to correct To Do column ID
    if: github.event.project_card.column_id == '######'
    runs-on: ubuntu-latest
    steps:
      - name: add to do label
        uses: andymckay/labeler@master
        with:
          add-labels: "To Do"
```

The following is the output we got:

```bash
- Set up job

Current runner version: '2.278.0'
Runner name: '############'
Runner group name: '########'
Machine name: '#####'
GITHUB_TOKEN Permissions
Runner is running behind proxy server 'http://proxy.####.com:pppp' for all HTTP requests.
Runner is running behind proxy server 'http://proxy.####.com:pppp' for all HTTPS requests.
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'andymckay/labeler@master'

- Remove old labeling

Run andymckay/labeler@master
  with:
    remove-labels: To Do, Assigned, In Progress, Testing, Done
    repo-token: ***
RequestError [HttpError]: request to https://api.github.com/repos/##############/issues/30 failed, reason: connect ETIMEDOUT ###.###.###.###:pppp
    at /home/github-runner/runner/########/001/_work/_actions/andymckay/labeler/master/node_modules/@octokit/request/dist-node/index.js:103:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async label (/home/github-runner/runner/########/001/_work/_actions/andymckay/labeler/master/label.js:45:33) {
  name: 'HttpError',
  status: 500,
  headers: {},
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/########/########/issues/30',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.28.9 Node.js/12.13.1 (Linux 4.15; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register], validate: [Object] }
  }
}
```

and

```bash
- Add to do label

Run andymckay/labeler@master
  with:
    add-labels: To Do
    repo-token: ***
RequestError [HttpError]: request to https://api.github.com/repos/##############/issues/30 failed, reason: connect ETIMEDOUT ###.###.###.###:pppp
    at /home/github-runner/runner/########/001/_work/_actions/andymckay/labeler/master/node_modules/@octokit/request/dist-node/index.js:103:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async label (/home/github-runner/runner/########/001/_work/_actions/andymckay/labeler/master/label.js:45:33) {
  name: 'HttpError',
  status: 500,
  headers: {},
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/########/########/issues/30',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.28.9 Node.js/12.13.1 (Linux 4.15; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register], validate: [Object] }
  }
}
```

Repo names, URLs and IPs redacted.
