### ISSUE TITLE
 Cannot read property 'pull_request' of undefined

### ISSUE THREAD

**Issue by hugo-goncalves-kununu** [andymckay/labeler#28]
It is not working when I am merging to master (but used to work before)

My workflow:
```
name: Add/remove labels when a PR is merged to master
on:
  pull_request:
    types: [ closed ]
    branches: [ master ]
jobs:
  merge_job:
    if: startsWith(github.event.ref, 'dependabot/') == false && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Add label approved
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          add-labels: "approved"
          remove-labels: "lab,ready to be reviewed,work in progress"
```

The error:
```
Run andymckay/labeler@master
TypeError: Cannot read property 'pull_request' of undefined
    at getIssueNumber (/home/runner/work/_actions/andymckay/labeler/master/label.js:32:59)
    at label (/home/runner/work/_actions/andymckay/labeler/master/label.js:50:21)
    at Object.<anonymous> (/home/runner/work/_actions/andymckay/labeler/master/label.js:99:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

This seems the same error reported and hopefully fixed on this PR https://github.com/andymckay/labeler/pull/27
