### ISSUE TITLE
GitHub CI output shows that label has been removed but it is not reflected on PR.

### ISSUE THREAD

**Issue by krmanik** [andymckay/labeler#32]
Hi, 
I am using this actions to remove labels from PR when it merged. But it seems it shows correct output but the labels is not removed from the PR. I have used it on fork repository and other repository it works there but on upstream it is not working. It only shows that task completed successfully.
 
```yaml
name: Remove Labels

on:
  pull_request_target:
    types: [ closed ]

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: write    
    runs-on: ubuntu-latest
    steps:
    - uses: andymckay/labeler@master
      with:
        remove-labels: > 
          Pending Merge, 
          Waiting For Feedback, 
          Needs Review, 
          Review High Priority, 
          Needs Second Approval,
          Blocked by dependency, 
          Needs a new dev, 
          squash-merge, 
          Keep Open, 
          Stable
```

CI Output
```
Run andymckay/labeler@master
Updated labels in 10676. Added: Removed: Pending Merge,Waiting For Feedback,Needs Review,Review High Priority,Needs Second Approval,Blocked by dependency,Needs a new dev,squash-merge,Keep Open,Stable.
```

On upstream, 
https://github.com/ankidroid/Anki-Android/pull/10676/files
