### ISSUE TITLE
Labels deleted on consecutive calls

### ISSUE THREAD

**Issue by fmulero** [andymckay/labeler#40]
### Version

1.0.4

### What steps will reproduce the bug?

Create a workflow with two o more `andymckay/labeler@1.0.4` consecutive steps  in the the same job adding labels. (We need to use a special token for some labels)

### What is the expected behavior?

All labels are added

### What do you see instead?

Last step removes the labels set in the previous steps. This is not happening always, the ratio is low, but happens regularly.

### Additional information

Running a workflow similar to the following one, `Step B` can remove the labels added in the `Step A`. I think the key point here is the call to the [get.issue](https://github.com/andymckay/labeler/blob/3a4296e9dcdf9576b0456050db78cfd34853f260/label.js#L62) function, probably it isn't returning the latest changes.

```yaml
name: 'Example'
on:
  project_card:
    types:
      - created
      - moved
permissions:
  issues: write
  pull-requests: write
jobs:
  label-card:
    runs-on: ubuntu-latest
    steps:
      - name: Step A
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: step-a
      - name: Step B
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: step-b
          repo-token: ${{ secrets.B_TOKEN}}
```
