### ISSUE TITLE
Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by mittalyashu** [andymckay/labeler#6]
`.github/workflows/label.yml`

```yml
name: Remove label on PR merge

on: 
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: andymckay/labeler@1.0.2
       with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          remove-labels: "work in progress, ready to merge"
```

```
> Run andymckay/labeler@1.0.2
TypeError: Cannot read property 'number' of undefined
    at label (/home/runner/work/_actions/andymckay/labeler/1.0.2/label.js:21:45)
    at Object.<anonymous> (/home/runner/work/_actions/andymckay/labeler/1.0.2/label.js:57:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```
